service:
  name: auction

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  #variables can be defined as below
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  # permission to write to DynamoDB Tables, also can be assigned at lambda functions
  iamRoleStatements:
    - Effect: Allow
      Action:
        #- dynamodb:* #this will allow for all dynamodb actions
        - dynamodb:PutItem
      Resource: # copy Amazon Resource Name(ARN), note using pseudo-parameters plugin
        # gives access to region and account number #{} - note hash symbol not $
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/AuctionsTable

# creating DynamoDB Tables
resources:
  Resources:
    # a new resource to create - an YAML object
    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable
        # still in free tier
        BillingMode: PAY_PER_REQUEST
        # note DynamoDB is schema less, can have any structure
        # always define a primary key as property
        # Attribute definitions are array of objects representing attributes of the table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S # strings
        KeySchema:
          - AttributeName: id
            KeyType: HASH

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          # POST method to create an auction - AWS will make necessary changes to Lambda
          method: POST
          path: /auction #note '/' is optional
