AuctionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: AuctionsTable-${self:provider.stage}
    # still in free tier
    BillingMode: PAY_PER_REQUEST
    # note DynamoDB is schema less, can have any structure
    # always define a primary key as property
    # Attribute definitions are array of objects representing attributes of the table
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S # strings
    KeySchema:
      - AttributeName: id
        KeyType: HASH
